hadoop.name-node: hdfs://localhost:9000
hadoop.namespace: /
#  hadoop:
#    fsUri: hdfs://132.232.44.82:9000

#端口
server:
  port: 8080

#log日志
logging:
  level:
    com:
      jeffrey:
       hadoopstudy: debug
